# Generated by Django 4.2.5 on 2023-11-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=150)),
                ('founder', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=3000)),
                ('production_year', models.IntegerField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make')),
            ],
        ),
    ]
