# Generated by Django 4.2.5 on 2023-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
